* ORG  
   
   Enable =org-roam=. It implements the Zettelkasten method in Emacs and uses a backing sqlite
   database, therefore =sqlite= must be on your path, at least for Emacs.
   
   #+BEGIN_SRC emacs-lisp
     (use-package org-roam
       :straight t
       :config
       (setq org-roam-directory "~/org")
       (add-hook 'after-init-hook 'org-roam-mode))
   #+END_SRC

   Enable additional languages for org-babel, namely Python.
   
   #+BEGIN_SRC emacs-lisp
     (org-babel-do-load-languages
       'org-babel-load-languages
       '((python . t)))
   #+END_SRC

   Enable tangle on save, big thanks to Diego Zamboni for his amazing booklet about
   [[https://leanpub.com/lit-config/read][/Literate Configuration/]].

   #+BEGIN_SRC emacs-lisp
     (add-hook 'org-mode-hook
	       (lambda () (add-hook 'after-save-hook #'org-babel-tangle
				    :append :local)))
   #+END_SRC
   
   Enable fancy UTF-8 characters for headings with =org-superstar=.
   
   #+BEGIN_SRC emacs-lisp
     (use-package org-superstar
       :straight t
       :hook ((org-mode . org-superstar-mode)))
   #+END_SRC
   
   Enable bigger headings for =org-mode=, this in my opinion makes it a bit easier to read org-mode
   buffer.
   
   #+BEGIN_SRC emacs-lisp
     (custom-set-faces
      '(fixed-pitch ((t (:family "Fira Code 9"))))
      '(org-level-1 ((t (:inherit outline-1 :height 1.25))))
      '(org-level-2 ((t (:inherit outline-2 :height 1.2))))
      '(org-level-3 ((t (:inherit outline-3 :height 1.15))))
      '(org-level-4 ((t (:inherit outline-4 :height 1.10))))
      '(org-level-5 ((t (:inherit outline-5 :height 1.05)))))
   #+END_SRC
   
   Enable the "vertical ruler" specifically for =org-mode=, TODO: it is worth considering to enable
   this for all text-mode buffers.
   
   #+BEGIN_SRC emacs-lisp
     (add-hook 'org-mode-hook (lambda ()
				(set-fill-column 120)
				(display-fill-column-indicator-mode)))
   #+END_SRC
   
   Enable =org-agenda=, used for task management and things like that. TODO: Currently it's
   underutilized and underconfigured.
   TODO: Also should I have a separate folder for school related things? Do I even have that folder?
   
   #+BEGIN_SRC emacs-lisp
     (setq org-agenda-files '("~/org" "~/org/school"))

     (setq org-agenda-custom-commands
	   '(("h" "Agenda and Home-related tasks"
	      ((agenda "")
	       (tags-todo "home")
	       (tags "garden")))
	     ("o" "Agenda and Office-related tasks"
	      ((agenda "")
	       (tags-todo "work")
	       (tags "office")))
	     ("i" "Agenda and School-related tasks"
	      ((agenda "")
	       (tags-todo "school")
	       (tags "school")))))

     (setq org-highest-priority ?A)
     (setq org-lowest-priority ?E)
     (setq org-default-priority ?B)
   #+END_SRC

   (Dis)enable alerts and notifications, which should hook into =org-agenda= notify 

   #+BEGIN_SRC emacs-lisp :tangle no
     (require 'org-alert)
     (require 'notifications)
   #+END_SRC
   
   Increase org-preview size
   
   #+BEGIN_SRC emacs-lisp
     (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.75))
   #+END_SRC
   
   Enable org-tikz previews, =imagemagick= must be installed.
   
   #+BEGIN_SRC emacs-lisp
     (add-to-list 'org-latex-packages-alist
		  '("" "tikz" t))

     (eval-after-load "preview"
       '(add-to-list 'preview-default-preamble "\\PreviewEnvironment{tikzpicture}" t))

     (setq org-latex-create-formula-image-program 'imagemagick)
   #+END_SRC
   
   Install =org-fragtop=, it will automatically toggle previews for LaTex segments under point.
   
   #+BEGIN_SRC emacs-lisp
     (use-package org-fragtog
       :straight t
       :hook (org-mode . org-fragtog-mode))
   #+END_SRC
   
** ORG Linkz
   
   Based on [[https://github.com/p-kolacz/org-linkz][org-linkz]].
   Remove validation link from exported html file.
   Currently doesn't work for somer reason, must debug why.

   #+NAME: org-linkz-html-validation-link
   #+BEGIN_SRC emacs-lisp
     (setq org-html-validation-link nil)
   #+END_SRC
   #+NAME: org-linkz
   #+BEGIN_SRC emacs-lisp
     (require 'org-protocol)
     (setq org-capture-templates
	   '(
	     ("o" "Link capture" entry
	      (file+headline "~/org/linkz.org" "INBOX")
	      "* %a %U"
	      :immediate-finish t)
	     ))
     (setq org-protocol-default-template-key "o")
   #+END_SRC
   
   Then a .desktop file is needed for Firefox/Chromium

   #+NAME: org-protocol-desktop
   #+BEGIN_SRC conf-desktop :tangle ~/.local/share/applications/org-protocol.desktop
     [Desktop Entry]
     Name=org-protocol
     Exec=emacsclient -n %u
     Type=Application
     Terminal=fale
     Categories=System;
     MimeType=x-scheme-handler/org-protocol;
   #+END_SRC
   
   Then a bookmark must be added into firefox with this location

   #+NAME: bookmark
   #+BEGIN_SRC javascript :tangle no
     javascript:location.href="org-protocol:///capture?url="+encodeURIComponent(location.href)+"&title="+encodeURIComponent(document.title||"[untitled page]")
   #+END_SRC
