;;
;; $Id: org-task-dump-logs-as-csv.el,v 196a830a575e 2016/04/16 15:26:31 pkgs $
;;


(load "org-task-dump-logs.el")

(defun hmw/csv-formatter(log-entry)
  "Format a 3-tuple into comma separated values."
  (insert (format "%s,%s,%s\n" (car log-entry)
		  (cadr log-entry)
		  (mapconcat 'identity (cddr log-entry) " "))))

(defun hmw/org-task-dump-logs-as-csv(csv-file-name &optional with-header)
  "Generate a CSV file of the state changes of a given task. The
data is saved in CSV-FILE-NAME. An optional CSV file header can
be generated by calling this function with the prefix argument or
by setting the optional WITH-HEADER parameter."
  (interactive "FSave as CSV file: \nP")
  (let ((log-entries (hmw/org-task-retrieve-logs)))
    (with-temp-buffer
      (if with-header (insert "FromState,ToState,Timestamp\n"))
      (mapc (lambda(e)(hmw/csv-formatter e)) (cdr log-entries))
      (write-file csv-file-name))))

(provide 'org-task-dump-logs-as-csv)
